### ISSUE TITLE
English and more...

### ISSUE THREAD

**Issue by kroenings** [w568w/fuckView#1]
Hi,
First it's the first time i'm using Github so please don't be upset if i'm not right here.
I recently saw your module and I think the idea is great!
Only problem I see right now is that the app (and nearly everythink I found about it also) is olny in chinese.
I understand chinese not a little bit, so I can't help you translate it into english.
**But,** if you or someone else translate it in english, I wan't to offer me for translating it into german.

I  would be happy about a respone and i wish you good programming 🙂

**Comment by w568w** [comment]
Hi,well,
Recently I am working hard on a usage guide and some bugs for the app,so translations are put off these days.I will finish my work soon,then I can translate it.You can watch the project and wait for a translation guide.
Anyway,thanks for your offer very much.:slightly_smiling_face:

**Comment by w568w** [comment]
Fuckview has been translated into English.Maybe now you can **fork** this repository and add more languages.
