### ISSUE TITLE
MIUI菜单显示不正常

### ISSUE THREAD

**Issue by reserveword** [w568w/fuckView#12]
Xposed版本:r90-beta2
净眼版本:0.9.2 experimental
Android版本:8.0
MIUI版本:10.2.2.0 国际稳定版
手机型号: MI 5 (gemini)

MIUI10当中广泛使用了居中悬浮窗作为设置菜单,安装净眼后这些菜单会出现不能正常显示的问题,会出现一个仅保留标题和取消按钮的底部窜浮窗.

比如在一个设置当中,没有净眼是这样的:
![选择设置项](https://user-images.githubusercontent.com/12995615/54350886-3bd83600-4689-11e9-8f98-5275ad36ab4a.png)
![正常弹窗](https://user-images.githubusercontent.com/12995615/54350869-34189180-4689-11e9-8057-d667a0cde858.jpg)

而在加载净眼之后则会变成这样的情况:
![不正常弹窗](https://user-images.githubusercontent.com/12995615/54350984-74780f80-4689-11e9-8269-83aabcffb496.png)

无法正常更改设置.

**Comment by w568w** [comment]
目前，这一问题可通过升级到 [LSPosed](https://github.com/LSPosed/LSPosed) 解决。
