### ISSUE TITLE
Can not mark advertisements

### ISSUE THREAD

**Issue by sir-harlekin** [w568w/fuckView#6]
In MyFitnessPal there are fixed spaces which show advertisements. I can block out any text or picture, but i can not "mark" this grey space. Will this be a feature in the future?

This space completely vanishes with MinMinGuard.

**Comment by w568w** [comment]
"Grey space" may refer to Google Ads containers or something like those.There will be a feature dedicated to Google Ads Blocking.
-------------------------------
“灰色空间”可能指Google广告容器或类似的控件。将会有专门用于Google广告屏蔽的功能。

**Comment by w568w** [comment]
"Gray space" may refer to a Google ads container or something like that.There will be a feature specifically designed for Google ad blocking someday.

**Comment by sir-harlekin** [comment]
Yes, it is a google ads container. Looking forward to beeing able so select and block them. Willing to do beta test any time.

**Comment by sir-harlekin** [comment]
How do i block google ads with the newest version 9.2.3? Grey space can not be selected.

**Comment by w568w** [comment]
Blocking should be enabled for each app in default without any settings and markings.  
If ads keep showing,please provide me with **the name of the application** to which I will try to adapt the module.

**Comment by sir-harlekin** [comment]
The app is https://play.google.com/store/apps/details?id=com.myfitnesspal.android

**Comment by w568w** [comment]
It doesn't seem that there are google ads in MyFitnessPal.Instead there is a Share Through Ad container.I will add support for sharethrough ads specifically,and I may check the reason why they cannot be marked a bit later.

**Comment by sir-harlekin** [comment]
Thanks for clarifying. To be honest i did not know the difference between google ad and Share Through Ad container.

**Comment by sir-harlekin** [comment]
With the newest build from https://fir.im/fuckview i can not go to the diary in the myfitnesspal app. i am stuck on the overview. elements get marked, but it is not possible to navigate through the app.

i suppose there is nothing i must select to block share through ad containers?

**Comment by w568w** [comment]
Yes, you needn't mark ads manually,for ads have been marked in fuckview beforehand.  
Besides,It should be a bug when you navigate through the app.The bug will be fixed at once.  
I hope it will solve your problem.

**Comment by sir-harlekin** [comment]
I can still not navigate in Myfitnesspal with build 24.

**Comment by w568w** [comment]
It is unnavigatable when you are marking in the app,or just using it normally?

**Comment by w568w** [comment]
And does `navigate` mean using the navigation drawer or switching the tab page in the application?  
Could you describe a bit more?

**Comment by sir-harlekin** [comment]
switching the tab pages in the application is not possible (left hand side has a hamburger menu, which registers no input). Its like there is kind of an invisible "overlay".

**Comment by w568w** [comment]
> switching the tab pages in the application is not possible (left hand side has a hamburger menu, which registers no input). Its like there is kind of an invisible "overlay".

Are you marking in the app or just using it normally?I will check whether the module has problems.

**Comment by sir-harlekin** [comment]
i try to use the app normally. i can not even switch to the parts of the app, wo i want to be marked.

**Comment by w568w** [comment]
> i try to use the app normally. i can not even switch to the parts of the app, wo i want to be marked.

I see.I'll check it.

**Comment by w568w** [comment]
No further information so I decide to close it. Reopen it if you still have any problems.
