### ISSUE TITLE
为啥里面的配置是你本机上的地址?

### ISSUE THREAD

**Issue by reserveword** [w568w/fuckView#8]
![image](https://user-images.githubusercontent.com/12995615/41705433-8d956b06-756b-11e8-8d4c-987290bf6c96.png)
像这样,原来的配置引用了绝对地址...而且那个app.iml不在repo里面,

**Comment by w568w** [comment]
不清楚Android Studio为何引用了绝对文件地址...但是`app.iml`不在文件中的原因应该是这个文件被加入了git的忽略上传文件名单里

**Comment by reserveword** [comment]
那么那个app.iml是不是这个应用的一部分呢?

**Comment by w568w** [comment]
app.iml是本地生成的，即使删除了，android studio在打开项目时也会重新生成，因此不必上传。
