### ISSUE TITLE
显示模块未启用,但实际上可以使用

### ISSUE THREAD

**Issue by reserveword** [w568w/fuckView#9]
在xposed installer 中启用(并重启)后仍然会提示没有启用,同时可以标记应用和屏蔽

**Comment by w568w** [comment]
> 在xposed installer 中启用(并重启)后仍然会提示没有启用

设置模块启用的代码在这里：  
https://github.com/w568w/fuckView/blob/fc91f9118f48de8cfd23558847ce2f5dc7d00a48/app/src/main/java/ml/qingsu/fuckview/hook/InitInjector.java#L49
似乎`loadPackageParam.classLoader`在某些设备上不可用，因此导致无论是否启用均显示"未启用"。
   这个问题到目前为止无解，是系统问题，似乎某些系统会对净眼进行分割，导致在某一部分找不到这个类。

> 同时可以标记应用和屏蔽

这个是正常情况，在对其他应用的劫持中，没有再使用到`loadPackageParam.classLoader`。
